### ISSUE TITLE
Example of JIT compilation misses an import

### ISSUE THREAD

**Issue by DanNegrut** [kks32-courses/sciml#1]
The first line of code in https://kks32-courses.github.io/sciml/lectures/07-ad/07-ad.html:
from jax import jit
should probably be:
from jax import jit, numpy as jnp

Otherwise, there's an error when evaluating the sin function. Full original code is here:
`
from jax import jit

@jit
def f(x):
    return jnp.sin(x)

print(f(1.0))
`

**Comment by kks32** [comment]
Thanks @DanNegrut ! Fixed it.

**Comment by DanNegrut** [comment]
I’m reading through that doc and found it very useful 😊
If I find other things, I’ll keep sending stuff your way.
I might also fork and send pull requests (but I was too lazy to do it).
Dan
---------------------------------------------
Bernard A. and Frances M. Weideman Professor
NVIDIA CUDA Fellow
Department of Mechanical Engineering
Department of Computer Science
University of Wisconsin - Madison
4150ME, 1513 University Avenue
Madison, WI 53706-1572
608 772 0914
http://sbel.wisc.edu/
http://projectchrono.org/
---------------------------------------------
